#!/usr/bin/env ruby
# frozen_string_literal: true

require "shopify_ruby_definitions"

definitions = [
  ENV["RUBY_BUILD_DEFINITIONS"],
  ShopifyRubyDefinitions::RubyVersions::VERSIONS_DIRECTORY,
].compact.join(":")

case ARGV.shift
when "versions"
  puts ShopifyRubyDefinitions::RubyVersions::ALL_VERSIONS
when "build"
  Process.exec({ "RUBY_BUILD_DEFINITIONS" => definitions }, "ruby-build", *ARGV)
when "env"
  puts %{export RUBY_BUILD_DEFINITIONS="#{definitions}"}
else
  $stderr.puts <<~USAGE
    Usage:  shopify-ruby list
            shopify-ruby build [-kpv] <definition> <prefix>
            shopify-ruby env
  USAGE
end
